server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.security: DEBUG
    org.demo.security.authentication: DEBUG

login:
  gitee:
    clientId: "d292f41e18f29500fbac712c22ee2f88eb77e4da2a5f0cb774d8db11c176c228"
    clientSecret: "a7180acf30329965b50bf8428f73dd68232423dc4b0a6a21bb10a25c82ff03f5"
    redirectUri: "http://localhost:8080/gitee-callback.html"