server:
  port: 8080  # 配置应用程序的服务器端口为 8080

logging:
  level:
    org.springframework.security: trace  # 设置 Spring Security 的日志级别为 TRACE，以便进行详细的调试日志记录

spring:
  security:
    user:
      name: user1  # 配置默认内存用户的用户名为 user1
      password: 123  # 配置默认内存用户的密码为 123
    oauth2:
      authorization-server:
        client:
          messaging-client:
            registration:
              client-id: "messaging-client"  # 配置 OAuth2 客户端的 ID 为 messaging-client
              client-secret: "{noop}secret"  # 配置 OAuth2 客户端的密钥，使用 {noop} 表示不进行加密
              client-authentication-methods:
                - "client_secret_basic"  # 配置客户端认证方法为 client_secret_basic
              authorization-grant-types:
                - "authorization_code"  # 配置授权类型为授权码模式
                - "refresh_token"  # 配置授权类型为刷新令牌模式
                - "client_credentials"  # 配置授权类型为客户端凭证模式
              redirect-uris:
                - "https://www.baidu.com"  # 配置授权成功后的重定向 URI
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/logged-out"  # 配置注销后的重定向 URI
              scopes:
                - "openid"  # 配置授权范围 openid
                - "profile"  # 配置授权范围 profile
                - "message.read"  # 配置授权范围 message.read
                - "message.write"  # 配置授权范围 message.write
            require-authorization-consent: true  # 配置客户端要求用户在授权时进行确认
